// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBk2s5MEV1B2yfKgbINU6jF31fsfVPGGIo',
    appId: '1:230828752811:web:c796a8819f4b8a79339cee',
    messagingSenderId: '230828752811',
    projectId: 'afitness-51a0d',
    authDomain: 'afitness-51a0d.firebaseapp.com',
    storageBucket: 'afitness-51a0d.firebasestorage.app',
    measurementId: 'G-GP56RCVXC0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnqqyg-knEUYN5hBBZQm7f0N9RW98r5U4',
    appId: '1:230828752811:android:8985e1cec038c727339cee',
    messagingSenderId: '230828752811',
    projectId: 'afitness-51a0d',
    storageBucket: 'afitness-51a0d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGF75MV0BdUF8_96JTpQRCJDRXpBhEKqU',
    appId: '1:230828752811:ios:696e3759d573ca46339cee',
    messagingSenderId: '230828752811',
    projectId: 'afitness-51a0d',
    storageBucket: 'afitness-51a0d.firebasestorage.app',
    iosBundleId: 'com.example.afitnessgym',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGF75MV0BdUF8_96JTpQRCJDRXpBhEKqU',
    appId: '1:230828752811:ios:696e3759d573ca46339cee',
    messagingSenderId: '230828752811',
    projectId: 'afitness-51a0d',
    storageBucket: 'afitness-51a0d.firebasestorage.app',
    iosBundleId: 'com.example.afitnessgym',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBk2s5MEV1B2yfKgbINU6jF31fsfVPGGIo',
    appId: '1:230828752811:web:c80325eb438ca6f9339cee',
    messagingSenderId: '230828752811',
    projectId: 'afitness-51a0d',
    authDomain: 'afitness-51a0d.firebaseapp.com',
    storageBucket: 'afitness-51a0d.firebasestorage.app',
    measurementId: 'G-3DZ5V9KP9F',
  );
}
